---
# file: system.yml

- name: system | Modify the number of open files by one process
  shell: ulimit -SHn 65535 creates=/etc/security/limits.d/nofile.conf

- name: system | Write nofile into the system file
  template: src=nofile.conf.j2 dest=/etc/security/limits.d/nofile.conf owner=root group=root mode=0644

- name: system | Modify the number of max user processes
  shell: ulimit -SHu 65535 creates=/etc/security/limits.d/nproc.conf

- name: system | Write nproc into the system file
  template: src=90-nproc.conf.j2 dest=/etc/security/limits.d/90-nproc.conf owner=root group=root mode=0644

- name: system | Write sysctl.conf
  sysctl: name="{{ item.name }}" value="{{ item.value }}" state=present reload=yes ignoreerrors=yes
  with_items:
    - { name: 'net.ipv4.ip_forward', value: '0' }
    - { name: 'net.ipv4.conf.default.rp_filter', value: '1' }
    - { name: 'net.ipv4.conf.default.accept_source_route', value: '0' }
    - { name: 'net.ipv4.tcp_syncookies', value: '1' }
    - { name: 'net.ipv4.tcp_tw_reuse', value: '1' }
    - { name: 'net.ipv4.tcp_fin_timeout', value: '3' }
    - { name: 'net.ipv4.tcp_max_tw_buckets', value: '10240' }
    - { name: 'net.ipv4.tcp_max_syn_backlog', value: '60000' }
    - { name: 'net.ipv4.ip_local_port_range', value: '10000 65000' }
    - { name: 'kernel.core_uses_pid', value: '1' }
    - { name: 'kernel.msgmnb', value: '65536' }
    - { name: 'kernel.msgmax', value: '65536' }
    - { name: 'kernel.shmmax', value: '68719476736' }
    - { name: 'kernel.shmall', value: '4294967296' }
    - { name: 'net.netfilter.nf_conntrack_max', value: '1000000' }
    - { name: 'kernel.unknown_nmi_panic', value: '0' }
    - { name: 'kernel.sysrq', value: '0' }
    - { name: 'fs.file-max', value: '3259355' }
    - { name: 'fs.inotify.max_user_watches', value: '10000000' }
    - { name: 'vm.swappiness', value: '10' }
    - { name: 'net.core.somaxconn', value: '16384' }
    - { name: 'net.core.wmem_max', value: '327679' }
    - { name: 'net.core.rmem_max', value: '327679' }
    - { name: 'net.core.netdev_max_backlog', value: '30000' }
